//
// Created by rotten on 17.01.23.
//

#ifndef DIRECTORYCHANGELOGGER_YAML_FORMATTER_H
#define DIRECTORYCHANGELOGGER_YAML_FORMATTER_H


class yaml_formatter {

};


#endif //DIRECTORYCHANGELOGGER_YAML_FORMATTER_H
